src/update_handler: fix uninitialized local
The local variable out_fd maybe used uninitialized after the label out.

It is initialized late in the function:

	out_fd = open(dest_slot->device, O_WRONLY);

But the code may goto before it is initialized, and thus used
uninitialized.

Fixes:

	src/update_handler.c: In function ‘img_to_boot_mbr_switch_handler’:
	src/update_handler.c:1249:3: error: ‘out_fd’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
	 1249 |   close(out_fd);
	      |   ^~~~~~~~~~~~~
	cc1: all warnings being treated as errors

Signed-off-by: Gaël PORTAY <gael.portay@collabora.com>